#!/bin/bash
# Submission script for Lemaitre3
#SBATCH --time=2-00:00:00 # days-hh:mm:ss
#
#SBATCH --cpus-per-task=15
#SBATCH --mem-per-cpu=2600 # megabytes
#SBATCH --partition=batch

export OMP_NUM_THREADS=15
export MKL_NUM_THREADS=15

mkdir genes # temp dir pour diamond
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-gen-contigs-database -f scaffolds.fasta -o CONTIGS.db -n 'contigs database'
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-get-sequences-for-gene-calls -c CONTIGS.db -o gene-calls.fasta
diamond blastx -d /CECI/proj/plgen/lcornet/Diamond/LICHEN.dmnd -q gene-calls.fasta -o gene-calls.dblastx -k 30 -e 1e-10 -f tab -p 10 -t genes
cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
/scratch/ulg/medgen/lcornet/lichen/physeter.pl gene-calls.dblastx --taxdir=/scratch/ulg/medgen/lcornet/lichen/TAXDIR/02-03-2020 --outfile=gene-calls-parser --taxon-list=/scratch/ulg/medgen/lcornet/lichen/contam-taxa.list --lca --anvio --tax-max-hits=50
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-import-taxonomy-for-genes -c CONTIGS.db -i gene-calls-anvio.tsv -p default_matrix
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-init-bam scaffolds.6126-S14_S14_R1_001-fastpstq.bam -o SAMPLE-01.bam
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-init-bam scaffolds.6126-S14_S14_R2_001-fastpstq.bam -o SAMPLE-02.bam
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-profile -i SAMPLE-01.bam -c CONTIGS.db --num-threads 15
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-profile -i SAMPLE-02.bam -c CONTIGS.db --num-threads 15
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-merge */PROFILE.db -o SAMPLES-MERGED -c CONTIGS.db
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-import-collection maxbin_results.txt -p SAMPLES-MERGED/PROFILE.db -c CONTIGS.db --collection-name "maxbin" --contigs-mode
singularity exec /scratch/ulg/medgen/lcornet/lichen/anvio6.simg anvi-import-collection metabat_results.txt -p SAMPLES-MERGED/PROFILE.db -c CONTIGS.db --collection-name "metabat" --contigs-mode
